config/routes.rb
Rails.application.routes.draw do
  root to: 'static_pages#home'
  get 'about', to: 'static_pages#about'
  get 'contact', to: 'static_pages#contact'
  get 'email', to: 'static_pages#email'



  resources :companies, only: %i[new create]

  devise_for :companies, skip: [:sessions, :passwords, :confirmations]

  # Move the devise_scope block here
  devise_scope :company do
    get '/sign_in', to: 'devise/sessions#new', as: :new_company_session
    post '/sign_in', to: 'devise/sessions#create', as: :company_session
    delete 'company/sign_out', to: 'devise/sessions#destroy', as: :destroy_company_session
    get 'company/password', to: 'devise/passwords#new', as: :new_company_password
    get 'company/password/edit', to: 'devise/passwords#edit', as: :edit_company_password
    put 'company/password', to: 'devise/passwords#update', as: :company_password
    post 'company/password', to: 'devise/passwords#create', as: :company_passwords
    get 'company/confirmation', to: 'devise/confirmations#show', as: :company_confirmation
    get 'company/confirmation/new', to: 'devise/confirmations#new', as: :new_company_confirmation
    post 'company/confirmation', to: 'devise/confirmations#create', as: :company_confirmations
  end

  namespace :reverse_auction do
    root to: 'dashboard#index'
    resources :auctions, except: :index do
      post '/register/', on: :member, to: 'auctions#register', as: :register
      resources :lots, only: %i[create update show destroy]
    end

    resources :lots, only: [] do
      post '/wish/', on: :member, to: 'lots#wish', as: :wish
      resources :bids, only: %i[new create destroy], shallow: true
    end

    get 'wishlist', to: 'lots#wishlist', as: :wishlist
    get '/lots-bid', to: 'bids#lots_bid', as: :lots_bid
    get '/registered', to: 'auctions#registered', as: :registered
    get '/live-auctions', to: 'auctions#live', as: :live
    get '/my-auctions', to: 'auctions#buyer_auctions', as: :my_auctions
  end

  devise_for :administrators, only: %i[sessions unlocks]
  namespace :admin do
    resources :auctions
    resources :auction_registrations
    resources :bids
    resources :categories
    resources :companies
    resources :lots
    resources :watched_lots

    root to: "auctions#index"
  end
  
  resources :company_onboardings do
    post '/approve/', on: :member, to: 'company_onboardings#approve', as: :approve
  end
end

app/controllers/static_pages_controller.rb
# frozen_string_literal: true

class StaticPagesController < ApplicationController
  def home; end

  def contact; end

  def about; end
end

app/helpers/static_pages_helper.rb
# frozen_string_literal: true

module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<% provide(:title, 'About us') %>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact us') %>

app/views/static_pages/email.html.erb
<div class="bg-light p-1 row rounded mx-auto justify-content-center">
  <div class="p-2 col-5 shadow">
    <%= image_tag 'email_illustration.jpg', class: 'img-fluid ' %>
  </div>
  <div class="bg-light p-2 col-6 shadow text-center">
    <div class="g-4 px-5">
      <h4 class="display-4">Welcome to <span class="text-primary my-0">Analytica</span></h4>
      <p class="text-center">
        An account with this email has been created on Analytica.
        Please confirm the account.
      </p>

      <%= link_to 'Confirm account', root_path,
        class: 'btn btn-primary mb-4' %>

      <p class="text-info">
        If you did not create an account on Analytica please ignore this email.
      </p>
    </div>
  </div>
</div>

app/views/static_pages/home.html.erb
<div class="bg-dark">
  <div class="container my-0">
    <header class="d-flex flex-wrap justify-content-center py-3">
      <a href="/" class="d-flex align-items-center mb-3 mb-md-0 me-md-auto text-dark text-decoration-none">
        <span class="fs-4 text-light">Analytica</span>
      </a>

      <ul class="nav nav-pills">
        <li class="nav-item"><a href="#" class="nav-link text-light">Find Tenders</a></li>
        <li class="nav-item"><a href="#" class="nav-link text-light">RFQs</a></li>
        <li class="nav-item"><%= link_to 'Contact us', contact_path, class: "nav-link text-light" %></li>
        <li class="nav-item"><%= link_to 'About us', about_path, class: "nav-link text-light" %></li>
      </ul>

      <div class="text-end">
        <%= link_to 'Login', new_company_session_path, class: 'btn btn-outline-light me-2' %>
        <%= link_to 'Sign up', new_company_onboarding_path, class: 'btn btn-light' %>
      </div>
    </header>
  </div>
</div>

<div class="bg-dark text-secondary px-4 py-5 mb-3 text-center">
  <div class="py-5">
    <h1 class="display-5 fw-bold text-white">
      <%= t('views.static_pages.home.entry_hero_title') %>
    </h1>
    <div class="col-lg-6 mx-auto">
      <p class="fs-5 mb-4">
        <%= t('views.static_pages.home.entry_hero_desc') %>
      </p>
      <div class="d-grid gap-2 d-sm-flex justify-content-sm-center">
        <%= link_to 'Create Account', new_company_onboarding_path,
                    class: 'btn btn-outline-info btn-lg px-4 me-sm-3 fw-bold'
        %>

        <%= link_to 'Log in', new_company_session_path,
                    class: 'btn btn-outline-light btn-lg px-4'
        %>
      </div>
    </div>
  </div>
</div>

<div class="container-fluid" id="features">
  <h1 class="m-5 display-4 text-center text-dark">
    <span class="font-weight-bold border-bottom border-5 rounded border-info">Discover Our Features</span>
  </h1>

  <div class="col-xxl-8 px-4" id="feature_one">
    <div class="row flex-lg-row align-items-center g-5 py-2">
      <div class="col-10 col-sm-8 col-lg-6">
        <%= image_tag 'istockphoto-1138748691-612x612.jpg', class: 'd-block mx-lg-auto img-fluid', alt: '', width: 700, height: 500, loading: 'lazy'%>
      </div>
      <div class="col-lg-6">
        <h1 class="display-5 fw-bold lh-1 mb-3">
          <%= t('views.static_pages.home.feature_one_title') %>
        </h1>
        <p class="lead">
          <%= t('views.static_pages.home.feature_one_desc').html_safe %>
        </p>
        <div class="d-grid gap-2 d-md-flex justify-content-md-start">
          <%= link_to 'Sign up to explore', new_company_onboarding_path,
                      class: 'btn btn-primary btn-lg px-4 me-md-2'
          %>
        </div>
      </div>
    </div>
  </div>
  <div class="col-xxl-8 px-4" id="feature_two">
    <div class="row flex-lg-row-reverse align-items-center g-5 py-2">
      <div class="col-10 col-sm-8 col-lg-6">
        <%= image_tag 'rfq.jpg', class: 'd-block mx-lg-auto img-fluid', alt: '', width: 700, height: 500, loading: 'lazy'%>
      </div>
      <div class="col-lg-6">
        <h1 class="display-5 fw-bold lh-1 mb-3">
          <%= t('views.static_pages.home.feature_two_title') %>
        </h1>
        <p class="lead">
          <%= t('views.static_pages.home.feature_two_desc').html_safe %>
        </p>
        <div class="d-grid gap-2 d-md-flex justify-content-md-start">
          <button type="button" class="text-white btn btn-info btn-lg px-4">Coming soon</button>
        </div>
      </div>
    </div>
  </div>
  <div class="col-xxl-8 px-4 pb-1" id="feature_three">
    <div class="row flex-lg-rowy align-items-center g-5 pt-5">
      <div class="col-10 col-sm-8 col-lg-6">
        <%= image_tag 'logistics.jpg', class: 'd-block mx-lg-auto img-fluid', alt: 'Logistsics image', width: 700, height: 500, loading: 'lazy'%>
      </div>
      <div class="col-lg-6">
        <h1 class="display-5 fw-bold lh-1 mb-3">
          <%= t('views.static_pages.home.feature_three_title') %>
        </h1>
        <p class="lead">
          <%= t('views.static_pages.home.feature_three_desc').html_safe %>
        </p>
        <div class="d-grid gap-2 d-md-flex justify-content-md-start">
          <button type="button" class="text-white btn btn-info btn-lg px-4">Coming soon</button>
        </div>
      </div>
    </div>
  </div>
</div>

<section id="sponsors" class="bg-light py-5">
  <div class="container">
    <h2 class="display-4 text-center">Our Sponsors</h2>
    <div class="row justify-content-center mt-4">
      <!-- Sponsor 1 -->
      <div class="col-md-3 col-sm-6 mb-4">
        <div class="sponsor-card">
          <span class="bi-heart"></span> <!-- Example of a Bootstrap -->
        </div>
      </div>

      <!-- Sponsor 2 -->
      <div class="col-md-3 col-sm-6 mb-4">
        <div class="sponsor-card">
          <span class="bi-truck"></span> <!-- Example of another Bootstrap -->
        </div>
      </div>

      <!-- Sponsor 3 -->
      <div class="col-md-3 col-sm-6 mb-4">
        <div class="sponsor-card">
          <span class="bi-truck"></span> <!-- Example of another Bootstrap -->
        </div>
      </div>

      <!-- Sponsor 4 -->
      <div class="col-md-3 col-sm-6 mb-4">
        <div class="sponsor-card">
          <span class="bi-truck"></span> <!-- Example of another Bootstrap -->
        </div>
      </div>

      <!-- Sponsor 5 -->
      <div class="col-md-3 col-sm-6 mb-4">
        <div class="sponsor-card">
          <span class="bi-truck"></span> <!-- Example of another Bootstrap -->
        </div>
      </div>

      <!-- Sponsor 6 -->
      <div class="col-md-3 col-sm-6 mb-4">
        <div class="sponsor-card">
          <span class="bi-truck"></span> <!-- Example of another Bootstrap -->
        </div>
      </div>

      <!-- Sponsor 7 -->
      <div class="col-md-3 col-sm-6 mb-4">
        <div class="sponsor-card">
        <span class="bi-truck"></span> <!-- Example of another Bootstrap -->
      </div>
    </div>

    <!-- Sponsor 8 -->
    <div class="col-md-3 col-sm-6 mb-4">
      <div class="sponsor-card">
        <span class="bi-truck"></span> <!-- Example of another Bootstrap -->
      </div>
    </div>
  </div>
  </div>
</section>

<div class="container bg-white">
  <h2 class="m-5 text-center display-4">Logistics jobs</h2>
  <div class="row mb-2">
    <div class="col-md-6">
      <div class="row g-0 border rounded flex-md-row mb-4 shadow-sm h-md-250 position-relative">
        <div class="col-auto d-none d-lg-block">
          <svg class="bd-placeholder-img p-3" width="125" height="125" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#55595c"></rect><text x="50%" y="50%" fill="#eceeef" dy=".3em">Thumbnail</text></svg>
        </div>
        <div class="col p-4 pt-3 d-flex flex-column position-static">
          <h3 class="mb-0">Job title</h3>
          <div class="card-text mb-1">Posted on: November 12, 2020</div>
          <p class="card-text text-muted mb-2">
            This is a wider card with supporting text below
            as a natural lead-in to additional content.
            This is a wider card with supporting text below
            as a natural lead-in to additional content.
          </p>
          <a href="#" class="stretched-link">Read more</a>
        </div>
      </div>
    </div>

    <div class="col-md-6">
      <div class="row g-0 border rounded flex-md-row mb-4 shadow-sm h-md-250 position-relative">
        <div class="col-auto d-none d-lg-block">
          <svg class="bd-placeholder-img p-3" width="125" height="125" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#55595c"></rect><text x="50%" y="50%" fill="#eceeef" dy=".3em">Thumbnail</text></svg>
        </div>
        <div class="col p-4 pt-3 d-flex flex-column position-static">
          <h3 class="mb-0">Job title</h3>
          <div class="card-text mb-1">Posted on: November 12, 2020</div>
          <p class="card-text text-muted mb-2">
            This is a wider card with supporting text below
            as a natural lead-in to additional content.
            This is a wider card with supporting text below
            as a natural lead-in to additional content.
          </p>
          <a href="#" class="stretched-link">Read more</a>
        </div>
      </div>
    </div>

    <div class="col-md-6">
      <div class="row g-0 border rounded flex-md-row mb-4 shadow-sm h-md-250 position-relative">
        <div class="col-auto d-none d-lg-block">
          <svg class="bd-placeholder-img p-3" width="125" height="125" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#55595c"></rect><text x="50%" y="50%" fill="#eceeef" dy=".3em">Thumbnail</text></svg>
        </div>
        <div class="col p-4 pt-3 d-flex flex-column position-static">
          <h3 class="mb-0">Job title</h3>
          <div class="card-text mb-1">Posted on: November 12, 2020</div>
          <p class="card-text text-muted mb-2">
            This is a wider card with supporting text below
            as a natural lead-in to additional content.
            This is a wider card with supporting text below
            as a natural lead-in to additional content.
          </p>
          <a href="#" class="stretched-link">Read more</a>
        </div>
      </div>
    </div>

    <div class="col-md-6">
      <div class="row g-0 border rounded flex-md-row mb-4 shadow-sm h-md-250 position-relative">
        <div class="col-auto d-none d-lg-block">
          <svg class="bd-placeholder-img p-3" width="125" height="125" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#55595c"></rect><text x="50%" y="50%" fill="#eceeef" dy=".3em">Thumbnail</text></svg>
        </div>
        <div class="col p-4 pt-3 d-flex flex-column position-static">
          <h3 class="mb-0">Job title</h3>
          <div class="card-text mb-1">Posted on: November 12, 2020</div>
          <p class="card-text text-muted mb-2">
            This is a wider card with supporting text below
            as a natural lead-in to additional content.
            This is a wider card with supporting text below
            as a natural lead-in to additional content.
          </p>
          <a href="#" class="stretched-link">Read more</a>
        </div>
      </div>
    </div>
  </div>
</div>