config/routes.rb
Rails.application.routes.draw do
  root to: 'static_pages#home'
  get 'about', to: 'static_pages#about'
  get 'contact', to: 'static_pages#contact'
  get 'email', to: 'static_pages#email'



  resources :companies, only: %i[new create]

  devise_for :companies, skip: [:sessions, :passwords, :confirmations]

  # Move the devise_scope block here
  devise_scope :company do
    get '/sign_in', to: 'devise/sessions#new', as: :new_company_session
    post '/sign_in', to: 'devise/sessions#create', as: :company_session
    delete 'company/sign_out', to: 'devise/sessions#destroy', as: :destroy_company_session
    get 'company/password', to: 'devise/passwords#new', as: :new_company_password
    get 'company/password/edit', to: 'devise/passwords#edit', as: :edit_company_password
    put 'company/password', to: 'devise/passwords#update', as: :company_password
    post 'company/password', to: 'devise/passwords#create', as: :company_passwords
    get 'company/confirmation', to: 'devise/confirmations#show', as: :company_confirmation
    get 'company/confirmation/new', to: 'devise/confirmations#new', as: :new_company_confirmation
    post 'company/confirmation', to: 'devise/confirmations#create', as: :company_confirmations
  end

  namespace :reverse_auction do
    root to: 'dashboard#index'
    resources :auctions, except: :index do
      post '/register/', on: :member, to: 'auctions#register', as: :register
      resources :lots, only: %i[create update show destroy]
    end

    resources :lots, only: [] do
      post '/wish/', on: :member, to: 'lots#wish', as: :wish
      resources :bids, only: %i[new create destroy], shallow: true
    end

    get 'wishlist', to: 'lots#wishlist', as: :wishlist
    get '/lots-bid', to: 'bids#lots_bid', as: :lots_bid
    get '/registered', to: 'auctions#registered', as: :registered
    get '/live-auctions', to: 'auctions#live', as: :live
    get '/my-auctions', to: 'auctions#buyer_auctions', as: :my_auctions
  end

  devise_for :administrators, only: %i[sessions unlocks]
  namespace :admin do
    resources :auctions
    resources :auction_registrations
    resources :bids
    resources :categories
    resources :companies
    resources :lots
    resources :watched_lots

    root to: "auctions#index"
  end
  
  resources :company_onboardings do
    post '/approve/', on: :member, to: 'company_onboardings#approve', as: :approve
  end
end

app/models/company_onboarding.rb
# frozen_string_literal: true

class CompanyOnboarding < ApplicationRecord
  include Company::Attachments
  include Company::Validations

  enum approval: { pending_review: 0, approved: 1, disapproved: 2 }
  validates :reason_for_disapproval, length: { maximum: 300 }

  has_many :tokens, as: :generator, dependent: :destroy

  def self.ransackable_attributes(_auth_object = nil)
    %w[
      about address approval buyer created_at email id
      location name phone seller terms_and_conditions updated_at
    ]
  end

  def self.ransackable_associations(_auth_object = nil)
    %w[
      certificate_of_incorporation_attachment certificate_of_incorporation_blob
      cr5_attachment cr5_blob cr6_attachment cr6_blob logo_attachment logo_blob
      tax_clearance_attachment tax_clearance_blob
    ]
  end
end

app/controllers/company_onboardings_controller.rb
# frozen_string_literal: true

class CompanyOnboardingsController < ApplicationController
  before_action :authenticate_administrator!, except: %i[new create]
  before_action :company_onboarding, except: %i[new create index]
  before_action :company_disaproved?, only: %i[edit update]
  before_action :token_valid?, only: %i[edit update]
  before_action :onboarding_valid?, except: %i[new create index]

  def new
    @company_onboarding = CompanyOnboarding.new
  end

  def create
    @company_onboarding = CompanyOnboarding.new(permitted_params)

    if @company_onboarding.save
      redirect_to root_path, flash: { notice: I18n.t('create.success', scope: i18n_scope) }
    else
      render :new
    end
  end

  def show; end

  def index
    @q = CompanyOnboarding.ransack(params[:q])
    @company_onboardings = @q.result(distinct: true)
  end

  def approve # rubocop:disable Metrics/AbcSize
    if company_onboarding.is_a?(CompanyOnboarding) && company_onboarding.pending_review?
      case approval_params[:approval]
      when 'approved'
        company_onboarding.tokens.create!(status: 0, purpose: 0)
        company_onboarding.update!(approval: :approved, approval_token: SecureRandom.urlsafe_base64(32))
        CompanyOnboardingMailer.with(company_onboarding: company_onboarding).approve.deliver_later
        redirect_to company_onboardings_path, flash: { notice: I18n.t('approved.success', scope: i18n_scope) }
      when 'disapproved'
        company_onboarding.disapproved!
        company_onboarding.tokens.create!(status: 0, purpose: 1)
        company_onboarding.update!(reason_for_disapproval: approval_params[:reason_for_disapproval])
        CompanyOnboardingMailer.with(
          company_onboarding: company_onboarding,
          reason_for_disapproval: approval_params[:reason_for_disapproval]
        ).disapprove.deliver_later
        redirect_to company_onboardings_path, flash: { notice: I18n.t('disapproved.success', scope: i18n_scope) }
      end
    else
      redirect_to company_onboardings_path, flash: { alert: I18n.t('approved.failure', scope: i18n_scope) }
    end
  end

  def edit; end

  def update
    if company_onboarding.update(permitted_params)
      redirect_to root_path, flash: { notice: I18n.t('update.success', scope: i18n_scope) }
      company_onboarding.tokens.where(status: 0, purpose: 1).destroy_all
    else
      render :edit
    end
  end

  private

  def approval_params
    params.require(:company_onboarding).permit(:approval, :reason_for_disapproval)
  end

  def i18n_scope
    'controllers.company_onboardings'
  end

  def company_onboarding
    @company_onboarding ||= CompanyOnboarding.find(params[:id])
  end

  def company_disaproved?
    unless company_onboarding.is_a?(CompanyOnboarding) && company_onboarding.disapproved?
      redirect_to root_path, flash: { alert: I18n.t('disapproved.failure', scope: i18n_scope) }
    end
  end

  def token_valid?
    unless company_onboarding.tokens.any? && company_onboarding.tokens.where(status: 0, purpose: 1).any?
      redirect_to root_path, flash: { alert: I18n.t('token.invalid', scope: i18n_scope) }
    end
  end

  def onboarding_valid?
    if company_onboarding.is_a?(CompanyOnboarding) && Company.exists?(email: company_onboarding.email)
      redirect_to root_path, flash: { alert: I18n.t('email.failure', scope: i18n_scope) }
    end
  end

  def permitted_params
    params.require(:company_onboarding).permit(
      :email, :name, :phone, :address, :location,
      :certificate_of_incorporation, :tax_clearance,
      :cr5, :cr6, :terms_and_conditions, :password,
      :password_confirmation, :current_password, :approval
    )
  end
end

app/helpers/company_onboardings_helper.rb
# frozen_string_literal: true

module CompanyOnboardingsHelper
end

app/views/company_onboardings/edit.html.erb
<%= javascript_include_tag "switch_tabs", "data-turbo-track": "reload", defer: true %>
<% provide(:title, 'Onboarding') %>
<div class="row bg-light mx-sm-auto my-sm-3 container p-2">
  <div class="col-sm-2 bg-light p-2 my-4" id="nav-tab" role="tablist">
    <button class="btn btn-outline-info mb-2 w-100 active" id="company-details-tab" data-bs-toggle="tab" data-bs-target="#company-details" type="button" role="tab" aria-controls="company-details" aria-selected="true">Company details</button>
    <button class="btn btn-outline-info mb-2 w-100" id="documents-tab" data-bs-toggle="tab" data-bs-target="#documents" type="button" role="tab" aria-controls="documents" aria-selected="false"> Documents</button>
  </div>
  
  <div class="col-sm-10 mx-sm-auto p-3 rounded shadow-sm">
    <div class="mb-3 px-3">
      <h2 class="fw-bold my-0">Edit account infomation</h2>
      <small class="my-2">
        Edit your account information to pass the approval process.
      </small>
    </div>

    <%= form_with(url: company_onboarding_path, model: @company_onboarding, html: { method: :patch, data: { turbo: false } }) do |f| %>
      <%= f.hidden_field :approval, value: :pending_review %>
      <%= f.hidden_field :reason_for_disapproval, value: '' %>
      <div class="tab-content" id="nav-tabContent">
        <%= render "shared/error_messages", object: @company_onboarding %>
        <div class="tab-pane fade show active" id="company-details" role="tabpanel" aria-labelledby="company-details-tab">
          <div class="container-fluid p-3 row fw-semibold">
            <div class="col-sm-5 mb-3">
              <%= f.label 'Company name', class: 'form-label my-0' %>
              <%= f.text_field :name, class: 'form-control', placeholder: "Analytica" %>
            </div>

            <div class="col-sm-5 mb-3">
              <%= f.label :phone, class: 'form-label my-0' %>
              <%= f.telephone_field :phone, class: 'form-control', placeholder: "(024) 0123457" %>
            </div>

            <div class="col-sm-10 mb-3">
              <%= f.label :email, class: 'form-label my-0' %>
              <%= f.email_field :email, class: 'form-control', placeholder: "you@example.com" %>
            </div>

            <div class="col-sm-5 mb-3">
              <%= f.label 'Street address', class: 'form-label my-0' %>
              <%= f.text_field :address, class: 'form-control', placeholder: "1234 Street" %>
            </div>

            <div class="col-sm-5 mb-3">
              <%= f.label :city, class: 'form-label my-0' %>
              <%= f.text_field :location, class: 'form-control', placeholder: "Harare" %>
            </div>
          
          </div>
          <div class="col-sm-2 p-2 mx-3 rounded">
            <%= link_to '#', class: "w-100 btn btn-info text-white", id: "next-button" do %>
              Next
            <% end %>
          </div>
        </div>
        
        <div class="tab-pane fade" id="documents" role="tabpanel" aria-labelledby="documents-tab">
          <div class="container-fluid p-3 row fw-semibold">
            <div class="col-6 mb-2">
              <%= f.label :certificate_of_incorporation, class: 'form-label' %>
              <%= f.file_field :certificate_of_incorporation,accept: 'application/pdf' , class: 'form-control' %>
            </div>

            <div class="col-6 mb-2">
              <%= f.label :tax_clearence, class: 'form-label' %>
              <%= f.file_field :tax_clearance,accept: 'application/pdf' , class: 'form-control' %>
            </div>

            <div class="col-6 mb-2">
              <%= f.label :cr5, class: 'text-uppercase form-label' %>
              <%= f.file_field :cr5, accept: 'application/pdf' , class: 'form-control' %>
            </div>

            <div class="col-6 mb-3">
              <%= f.label :cr6, class: 'text-uppercase form-label' %>
              <%= f.file_field :cr6, accept: 'application/pdf', class: 'form-control' %>
            </div>

            <div class="form-check">
              <%= f.check_box :terms_and_conditions, class: 'form-check-input border-dark' %>
              <%= f.label 'I agree to the terms and conditions.', class:"form-check-label" %>
            </div>

            <div class="row col-sm-10 p-2 mx-3 rounded justify-content-center">
              <%= f.submit "Finish", class: "btn btn-primary btn-lg w-50 text-center" %>
            </div>
          </div>
          
          <div class="col-sm-2 p-2 mx-3 rounded">
            <%= link_to '#', class: "w-100 btn btn-info text-white", id: "previous-button" do %>
              Previous
            <% end %>
          </div>
        </div>
      </div>
      
    <% end %>
    
  </div>
</div>

app/views/company_onboardings/index.html.erb
<div class="container-fluid p-lg-5 overflow-hidden">
  <%= link_to 'BACK TO DASHBOARD', admin_root_path, class: 'btn btn-outline-primary mb-2 fw-bold' %>

  <h1 class="display-3 mb-5">Accounts pending approval</h1>

  <div class="">
    <%= render 'shared/ransack_search', data: { search_attributes: :name_or_phone_or_email_cont, button_class: 'btn-primary' } %>
    
    <table class="table table-striped shadow">
      <thead>
      <tr>
        <th scope="col">Company</th>
        <th scope="col">Email</th>
        <th scope="col">Phone</th>
        <th scope="col">Status</th>
        <th scope="col"></th>
      </tr>
      </thead>
      <tbody>
        <% @company_onboardings.each do |company_onboarding| %>
          <tr>
            <th scope="row" class="col-sm-4"><%= company_onboarding.name %></th>
            <td class="col-sm-3"><%= company_onboarding.email %></td>
            <td class="col-sm-3"><%= company_onboarding.phone %></td>
            <td class="col-sm-2"><%= company_onboarding.approval.split('_').join(' ').capitalize %></td>
            <td class="col-sm-1">
              <%= link_to company_onboarding_path(company_onboarding) do%>
                <i class="rounded py-1 px-2 btn btn-outline-info bi-eye-fill"></i>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/company_onboardings/new.html.erb
<%= javascript_include_tag "switch_tabs", "data-turbo-track": "reload", defer: true %>
<% provide(:title, 'Onboarding') %>
<div class="row bg-light mx-sm-auto my-sm-3 container p-2">
  <div class="col-sm-2 bg-light p-2 my-4" id="nav-tab" role="tablist">
    <button class="btn btn-outline-info mb-2 w-100 active" id="company-details-tab" data-bs-toggle="tab" data-bs-target="#company-details" type="button" role="tab" aria-controls="company-details" aria-selected="true">Company details</button>
    <button class="btn btn-outline-info mb-2 w-100" id="documents-tab" data-bs-toggle="tab" data-bs-target="#documents" type="button" role="tab" aria-controls="documents" aria-selected="false"> Documents</button>
  </div>
  
  <div class="col-sm-10 mx-sm-auto p-3 rounded shadow-sm">
    <div class="mb-3 px-3">
      <h2 class="fw-bold my-0">Get started now!</h2>
      <small class="my-2">
        Already registered?
        <%= link_to "Sign in", new_company_session_path, class: "text-primary text-decoration-none" %>
        to your account instead.
      </small>
    </div>

    <%= form_with(url: company_onboardings_path, model: @company_onboarding, html: { method: :post, data: { turbo: false } }) do |f| %>

      <div class="tab-content" id="nav-tabContent">
        <%= render "shared/error_messages", object: @company_onboarding %>
        <div class="tab-pane fade show active" id="company-details" role="tabpanel" aria-labelledby="company-details-tab">
          <div class="container-fluid p-3 row fw-semibold">
            <div class="col-sm-5 mb-3">
              <%= f.label 'Company name', class: 'form-label my-0' %>
              <%= f.text_field :name, class: 'form-control', placeholder: "Analytica" %>
            </div>

            <div class="col-sm-5 mb-3">
              <%= f.label :phone, class: 'form-label my-0' %>
              <%= f.telephone_field :phone, class: 'form-control', placeholder: "(024) 0123457" %>
            </div>

            <div class="col-sm-10 mb-3">
              <%= f.label :email, class: 'form-label my-0' %>
              <%= f.email_field :email, class: 'form-control', placeholder: "you@example.com" %>
            </div>

            <div class="col-sm-5 mb-3">
              <%= f.label 'Street address', class: 'form-label my-0' %>
              <%= f.text_field :address, class: 'form-control', placeholder: "1234 Street" %>
            </div>

            <div class="col-sm-5 mb-3">
              <%= f.label :city, class: 'form-label my-0' %>
              <%= f.text_field :location, class: 'form-control', placeholder: "Harare" %>
            </div>
          
          </div>
          <div class="col-sm-2 p-2 mx-3 rounded">
            <%= link_to '#', class: "w-100 btn btn-info text-white", id: "next-button" do %>
              Next
            <% end %>
          </div>
        </div>
        
        <div class="tab-pane fade" id="documents" role="tabpanel" aria-labelledby="documents-tab">
          <div class="container-fluid p-3 row fw-semibold">
            <div class="col-6 mb-2">
              <%= f.label :certificate_of_incorporation, class: 'form-label' %>
              <%= f.file_field :certificate_of_incorporation,accept: 'application/pdf' , class: 'form-control' %>
            </div>

            <div class="col-6 mb-2">
              <%= f.label :tax_clearence, class: 'form-label' %>
              <%= f.file_field :tax_clearance,accept: 'application/pdf' , class: 'form-control' %>
            </div>

            <div class="col-6 mb-2">
              <%= f.label :cr5, class: 'text-uppercase form-label' %>
              <%= f.file_field :cr5, accept: 'application/pdf' , class: 'form-control' %>
            </div>

            <div class="col-6 mb-3">
              <%= f.label :cr6, class: 'text-uppercase form-label' %>
              <%= f.file_field :cr6, accept: 'application/pdf', class: 'form-control' %>
            </div>

            <div class="form-check">
              <%= f.check_box :terms_and_conditions, class: 'form-check-input border-dark' %>
              <%= f.label 'I agree to the terms and conditions.', class:"form-check-label" %>
            </div>

            <div class="row col-sm-10 p-2 mx-3 rounded justify-content-center">
              <%= f.submit "Finish", class: "btn btn-primary btn-lg w-50 text-center" %>
            </div>
          </div>
          
          <div class="col-sm-2 p-2 mx-3 rounded">
            <%= link_to '#', class: "w-100 btn btn-info text-white", id: "previous-button" do %>
              Previous
            <% end %>
          </div>
        </div>
      </div>
      
    <% end %>
    
  </div>
</div>

app/views/company_onboardings/show.html.erb
<div class="g-2 row p-5">
  <h1 class="text-center my-3">Company Onboarding</h1>
  <div class="col-sm-12 mx-auto">
    <%= link_to 'BACK TO DASHBOARD', admin_root_path, class: 'btn btn-outline-primary mb-2 fw-bold' %>

    <div class="row rounded shadow p-lg-4">
      
      <div class="col-sm-3 p-2">
                
        <button class="btn btn-outline-info mb-2" data-bs-toggle="modal" data-bs-target="#certificate_of_incorporation">Certificate Of Incorporation</button>
        <%= render 'shared/pdf_reader', data: { 
            document_title: 'Certificate of Incorporation',
            pdf_path: rails_blob_path(@company_onboarding.certificate_of_incorporation),
            modal_id: 'certificate_of_incorporation' 
          } 
        %>
        <button class="btn btn-outline-info mb-2" data-bs-toggle="modal" data-bs-target="#tax_clearence_document">Tax Clearence Document</button>
        <%= render 'shared/pdf_reader', data: { 
            document_title: 'Tax Clearence Document',
            pdf_path: rails_blob_path(@company_onboarding.tax_clearance),
            modal_id: 'tax_clearence_document' 
          } 
        %>
        <button class="btn btn-outline-info mb-2" data-bs-toggle="modal" data-bs-target="#cr5"> CR5 Document</button>
        <%= render 'shared/pdf_reader', data: { 
            document_title: 'CR5 Document',
            pdf_path: rails_blob_path(@company_onboarding.cr5),
            modal_id: 'cr5' 
          } 
        %>
        <button class="btn btn-outline-info mb-2" data-bs-toggle="modal" data-bs-target="#cr6"> CR6 Document</button>
        <%= render 'shared/pdf_reader', data: { 
            document_title: 'CR6 Document',
            pdf_path: rails_blob_path(@company_onboarding.cr6),
            modal_id: 'cr6' 
          } 
        %>
      </div>

      <div class="col-sm-9 mx-auto">
        <h3 class="fw-bold">
          Name:
          <span class=" fw-normal float-end">
            <%= @company_onboarding.name %>
          </span>
        </h3>

        <h3 class="fw-bold">
          Email:
          <span class=" fw-normal float-end">
            <%= @company_onboarding.email %>
          </span>
        </h3>

        <h3 class="fw-bold">
          Phone:
          <span class=" fw-normal float-end">
            <%= @company_onboarding.phone %>
          </span>
        </h3>

        <h3 class="fw-bold">
          Address:
          <span class=" fw-normal float-end">
            <%= @company_onboarding.address %>
          </span>
        </h3>

        <h3 class="fw-bold">
          City:
          <span class=" fw-normal float-end">
            <%= @company_onboarding.location %>
          </span>
        </h3>

        <h3 class="fw-bold">
          Terms and conditions:
          <span class=" fw-normal float-end">
            <%= @company_onboarding.terms_and_conditions ? 'Accepted' : 'Not accepted' %>
          </span>
        </h3>

        <h3 class="fw-bold ">
          Created at:
          <span class=" fw-normal float-end">
            <%= @company_onboarding.created_at&.strftime('%d %b, %Y') %>
          </span>
        </h3>

        <div class="row my-5">
          <div class="col-sm-2">
            <button class="btn btn-warning text-white" data-bs-toggle="modal" data-bs-target="#disapprove">Disapprove</button>
          </div>
          <div class="col-sm-2">
            <%= form_with model: @company_onboarding, url: approve_company_onboarding_path(@company_onboarding), method: :post, data: { turbo: false } do |f| %>
              <%= f.hidden_field :approval, value: 'approved' %>
              <%= f.submit 'Approve', class: 'btn btn-primary' %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="modal fade"class="modal fade" id="disapprove" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLiveLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="disapproveLabel">Disapprove account</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <%= form_with model: @company_onboarding, url: approve_company_onboarding_path(@company_onboarding), method: :post, data: { turbo: false } do |f| %>
          <%= f.label :reason_for_disapproval, class: 'form-label' %>
          <%= f.hidden_field :approval, value: 'disapproved' %>
          <%= f.text_area :reason_for_disapproval, class: 'form-control mb-3' %>
          <%= f.submit 'Submit', class: 'btn btn-primary' %>
        <% end %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Discard</button>
      </div>
    </div>
  </div>
</div>