config/routes.rb
Rails.application.routes.draw do
  root to: 'static_pages#home'
  get 'about', to: 'static_pages#about'
  get 'contact', to: 'static_pages#contact'
  get 'email', to: 'static_pages#email'



  resources :companies, only: %i[new create]

  devise_for :companies, skip: [:sessions, :passwords, :confirmations]

  # Move the devise_scope block here
  devise_scope :company do
    get '/sign_in', to: 'devise/sessions#new', as: :new_company_session
    post '/sign_in', to: 'devise/sessions#create', as: :company_session
    delete 'company/sign_out', to: 'devise/sessions#destroy', as: :destroy_company_session
    get 'company/password', to: 'devise/passwords#new', as: :new_company_password
    get 'company/password/edit', to: 'devise/passwords#edit', as: :edit_company_password
    put 'company/password', to: 'devise/passwords#update', as: :company_password
    post 'company/password', to: 'devise/passwords#create', as: :company_passwords
    get 'company/confirmation', to: 'devise/confirmations#show', as: :company_confirmation
    get 'company/confirmation/new', to: 'devise/confirmations#new', as: :new_company_confirmation
    post 'company/confirmation', to: 'devise/confirmations#create', as: :company_confirmations
  end

  namespace :reverse_auction do
    root to: 'dashboard#index'
    resources :auctions, except: :index do
      post '/register/', on: :member, to: 'auctions#register', as: :register
      resources :lots, only: %i[create update show destroy]
    end

    resources :lots, only: [] do
      post '/wish/', on: :member, to: 'lots#wish', as: :wish
      resources :bids, only: %i[new create destroy], shallow: true
    end

    get 'wishlist', to: 'lots#wishlist', as: :wishlist
    get '/lots-bid', to: 'bids#lots_bid', as: :lots_bid
    get '/registered', to: 'auctions#registered', as: :registered
    get '/live-auctions', to: 'auctions#live', as: :live
    get '/my-auctions', to: 'auctions#buyer_auctions', as: :my_auctions
  end

  devise_for :administrators, only: %i[sessions unlocks]
  namespace :admin do
    resources :auctions
    resources :auction_registrations
    resources :bids
    resources :categories
    resources :companies
    resources :lots
    resources :watched_lots

    root to: "auctions#index"
  end
  
  resources :company_onboardings do
    post '/approve/', on: :member, to: 'company_onboardings#approve', as: :approve
  end
end

app/models/lot.rb
# frozen_string_literal: true

class Lot < ApplicationRecord
  before_create :assign_lot_number, :set_location

  belongs_to :company
  belongs_to :auction

  has_many :bids, dependent: :destroy
  has_many :watched_lots, dependent: :destroy

  validates :title, presence: true

  validate :auction_expired?
  validate :locations
  validate :company_is_buyer?

  def collect(company_id)
    watched_lots.create!(lot_id: id, company_id: company_id)
  end

  def collected?(company_id)
    watched_lot = WatchedLot.find_by(lot_id: id, company_id: company_id)
    watched_lot.present?
  end

  def winning_bid
    bids.last
  end

  def winner
    return unless auction.expired?

    bids&.last&.company
  end

  def current_winner
    return if auction.expired?

    bids&.last&.company
  end

  private

  def auction_expired?
    return if auction.blank?

    if Time.current > auction.deadline.to_time
      errors.add(:base, I18n.t('activerecord.errors.models.lot.errors.deadline_passed'))
    end
  end

  def locations
    return if auction.blank?

    if auction.location != location
      errors.add(:base,
                 I18n.t('activerecord.errors.models.lot.errors.different_location'))
    end
  end

  def company_is_buyer?
    return if company.blank?

    errors.add(:base, I18n.t('activerecord.errors.models.lot.errors.only_buyers')) unless company.buyer?
  end

  def assign_lot_number
    max_lot_number = auction.lots.maximum(:lot_number) || 0
    self.lot_number = max_lot_number + 1
  end

  def set_location
    self.location = auction.location
  end
end

app/controllers/admin/lots_controller.rb
# frozen_string_literal: true

class Admin::LotsController < Admin::ApplicationController
end

app/controllers/reverse_auction/application_controller.rb
# frozen_string_literal: true

class ReverseAuction::ApplicationController < ApplicationController
  before_action :authenticate_company!
  before_action :current_company
  layout 'reverse_auction_application'
end

app/controllers/reverse_auction/auctions_controller.rb
# frozen_string_literal: true

class ReverseAuction::AuctionsController < ReverseAuction::ApplicationController
  before_action :permitted_access?, only: %i[edit update destroy extend_deadline]

  def new
    @auction = Auction.new
  end

  def create
    @auction = current_company.auctions.build(permitted_params)

    if @auction.save
      redirect_to edit_reverse_auction_auction_path(@auction),
                  flash: { notice: I18n.t('controllers.auctions.create_success') }
    else
      flash[:alert] = @auction.errors.full_messages.join(',')
      render :new
    end
  end

  def show
    @lots = auction.lots.order(:lot_number)
    @bid = Bid.new
  end

  def live
    @live_auctions = Auction.where(location: current_company.location, expired: false)
  end

  def buyer_auctions
    @buyer_auctions = Auction.where(company: current_company)
  end

  def registered
    registrations = AuctionRegistration.where(company_id: current_company.id).pluck(:auction_id)
    @registered_auctions = Auction.where(expired: false, id: registrations).order(deadline: :asc)
  end

  def edit
    @lot = Lot.new
    @lots = auction.lots
  end

  def update
    if auction.update(permitted_params)
      redirect_to edit_reverse_auction_auction_path(auction),
                  flash: { notice: I18n.t('controllers.auctions.update_success') }
    else
      flash[:alert] = auction.errors.full_messages.join(',')
      render :edit
    end
  rescue StandardError
    flash[:alert] = I18n.t('controllers.something_wrong')
    render :edit
  end

  def destroy
    if auction.destroy!
      redirect_to reverse_auction_auctions_path, flash: { notice: I18n.t('controllers.auctions.delete_success') }
    else
      redirect_to request.referer, flash: { alert: auction.errors.full_messages.join(',') }
    end
  rescue StandardError
    redirect_to request.referer, flash: { alert: I18n.t('controllers.something_wrong') }
  end

  def extend_deadline
    if auction.update(deadline: auction.deadline.to_time + params[:auction][:extended_days].to_i.days)
      redirect_to edit_reverse_auction_auction_path(auction),
                  flash: { notice: "The auction has been extended by #{params[:auction][:extended_days]} days." }
    else
      redirect_to request.referer, flash: { alert: I18n.t('controllers.something_wrong') }
    end
  end

  def register
    registration = AuctionRegistration.new(company_id: current_company.id, auction_id: auction.id)

    if registration.save
      redirect_to reverse_auction_auction_path(registration.auction),
                  flash: { notice: I18n.t('controllers.auctions.register_success') }
    else
      redirect_to reverse_auction_auction_path(auction), flash: { alert: registration.errors.full_messages }
    end
  end

  private

  def auction
    @auction = Auction.find(params[:id] || params[:auction_id])
  rescue ActiveRecord::RecordNotFound
    flash[:alert] = I18n.t('controllers.auctions.auction_not_found')
  end

  def company_is_buyer?
    flash[:alert] = I18n.t('controllers.auctions.company_not_buyer') unless current_company.buyer
  end

  def permitted_access?
    unless auction.company_id == current_company.id
      redirect_to reverse_auction_auctions_path, flash: { notice: I18n.t('controllers.auctions.unauthorized') }
    end
  end

  def permitted_params
    params.require(:auction).permit(
      :title, :description, :notes,
      :location, :start, :deadline,
      :image, :category_ids
    )
  end
end

app/controllers/reverse_auction/bids_controller.rb
# frozen_string_literal: true

class ReverseAuction::BidsController < ReverseAuction::ApplicationController
  before_action :permitted_params, only: :create

  def lots_bid
    @lots = current_company.lots_bid
    @bid = Bid.new
  end

  def new
    @bid = Bid.new
  end

  def create
    @bid = current_company.bids.build(permitted_params)
    @bid.lot = lot
    @bid.location = lot.auction.location

    if @bid.save
      if request.referer.present?
        redirect_to request.referer, flash: {
          notice: I18n.t('controllers.bids.create_success')
        }
      end
    else
      render 'new'
    end
  end

  def destroy
    if bid.destroy && request.referer.present?
      redirect_to request.referer, flash: { notice: I18n.t('controllers.bids.destroy_success') }
    end
  end

  private

  def auction
    @auction = Auction.find(params[:auction_id])
  end

  def bid
    @bid = Bid.find(params[:id])
  end

  def lot
    @lot = Lot.find(params[:lot_id])
  end

  def permitted_params
    params.require(:bid).permit(:amount, :delivery_options, images: [])
  end
end

app/controllers/reverse_auction/dashboard_controller.rb
# frozen_string_literal: true

class ReverseAuction::DashboardController < ReverseAuction::ApplicationController
  def index; end
end

app/controllers/reverse_auction/lots_controller.rb
# frozen_string_literal: true

class ReverseAuction::LotsController < ReverseAuction::ApplicationController
  before_action :permitted_access?, except: %i[wishlist wish show]
  before_action :lot, only: %i[show destroy wish]

  def show
    @bid = Bid.new
  end

  def create
    @lot = auction.lots.build(permitted_params)
    @lot.company = auction.company
    @lot.location = auction.location

    if @lot.save
      redirect_to edit_reverse_auction_auction_path(auction), flash: { notice: t('controllers.lots.create.success') }
    else
      redirect_to edit_reverse_auction_auction_path(auction), flash: { alert: t('controllers.lots.create.failure') }
    end
  end

  def destroy
    if lot.destroy
      redirect_to edit_reverse_auction_auction_path(auction), flash: { notice: t('controllers.lots.destroy.success') }
    else
      flash[:alert] = auction.errors.full_messages
    end
  end

  # rubocop:disable Metrics/PerceivedComplexity
  def wish
    collection = WatchedLot.find_by(company: current_company, lot: lot)

    if collection.is_a?(WatchedLot)
      if collection.destroy
        notice = t('controllers.lots.collect.removal')
      else
        alert = 'There was an error removing lot from wishlist. Try again!'
      end
    else
      collection = WatchedLot.new(company: current_company, lot: lot)
      if collection.save
        notice = t('controllers.lots.collect.collection')
      else
        alert = 'Something went wrong while whishlisting the lot. Try again'
      end
    end

    redirect_to request.referer, flash: { notice: notice || alert } if request.referer.present?
  end
  # rubocop:enable Metrics/PerceivedComplexity

  def wishlist
    @lots = current_company.collected_lots
    @bid = Bid.new
  end

  private

  def auction
    @auction = Auction.find(params[:auction_id])
  end

  def lot
    @lot = Lot.find(params[:id])
  end

  def permitted_access?
    unless auction.company_id == current_company.id
      redirect_to reverse_auction_auctions_path, flash: { notice: I18n.t('controllers.auctions.unauthorized') }
    end
  end

  def permitted_params
    params.require(:lot).permit(:title, :quantity, :asking_price, :condition)
  end
end

app/helpers/lots_helper.rb
# frozen_string_literal: true

module LotsHelper
  def lost_lot?(company, lot, bids = lot.bids)
    return false if bids.empty?

    bids.any? && bids.last.company != company && bids.companies.include?(company)
  end

  def won_lot?(lot, company, bids = lot.bids)
    return false if bids.empty?

    bids.last.company == company && lot.auction.expired?
  end
end

app/helpers/reverse_auction/dashboard_helper.rb
# frozen_string_literal: true

module ReverseAuction::DashboardHelper
end

app/views/reverse_auction/lots/show.html.erb
<div class="container">
  <nav>
    <div class="nav nav-tabs mb-3" id="nav-tab" role="tablist">
      <button class="nav-link active" id="nav-home-tab" data-bs-toggle="tab" data-bs-target="#nav-home" type="button" role="tab" aria-controls="nav-home" aria-selected="true">Lot</button>
      <button class="nav-link" id="nav-profile-tab" data-bs-toggle="tab" data-bs-target="#nav-profile" type="button" role="tab" aria-controls="nav-profile" aria-selected="false">Bids</button>
    </div>
  </nav>

  <div class="tab-content" id="nav-tabContent">
    <div class="tab-pane fade show active" id="nav-home" role="tabpanel" aria-labelledby="nav-home-tab">
      <div class="tab-pane fade show active" id="lot" role="tabpanel" aria-labelledby="lot-tab">
        <div class="row justify-content-center m-sm-5">
          <div class="p-1 rounded-5 shadow px-5 col-sm-10">
            <span class="small fw-semibold mb-1">LOT NUMBER: #<%= @lot&.lot_number %></span>
            <h1 class="display-3">
              <%= @lot&.title.capitalize %>
              <%= link_to wish_reverse_auction_lot_path(@lot), data: {'turbo_method': :post} do %>
                <% if @lot&.collected?(current_company.id) %>
                  <i class="bi-bookmark-heart-fill text-info float-end"></i>
                <% else %>
                  <i class="bi-bookmark-heart text-info float-end"></i>
                <% end %>
              <% end %>
            </h1>

            <h4 class="h4">
              <i class="bi-cash-stack"></i>
              Asking price: $<%= currency_format @lot&.asking_price * 100 %>
            </h4>

            <% if @lot&.bids.any? %>
              <h4 class="">
                <i class="text-dark bi-coin"></i>
                Current bid: $<%= currency_format @lot&.winning_bid&.amount * 100 %>
              </h4>
            <% end %>

            <h4 class="h4">
              <i class="bi-info-circle"></i> Condition:
              <%= @lot&.condition&.capitalize %>
            </h4>

            <h4 class="h4">
              <i class="bi-geo"></i> Location:
              <%= @lot&.location %>
            </h4>
          </div>
        </div>
      </div>
    </div>

    <div class="tab-pane fade" id="nav-profile" role="tabpanel" aria-labelledby="nav-profile-tab">
      <div class="row justify-content-center p-1 rounded-4 shadow">
        <% if @lot&.bids.empty? %>
          <h1 class="display-3 text-center mb-sm-3"> Be the first to bid! </h1>
          <p class="fw-bold text-center">The starting bid for this lot is
            <span class="h5 text-primary">$<%= @lot&.asking_price %>.00</span>
          </p>
          <p class="text-center">
            <span class="btn btn-info px-4 fw-bold text-white" data-bs-toggle="modal"
                  data-bs-target="#new-bid">Bid</span>
          </p>
        <% end %>

        <% if lost_lot?(current_company, @lot) && !@lot.auction.expired? %>
          <h1 class="display-3 text-center mb-sm-3">
            You have been <span class="fw-bold"> outbid!</span>
          </h1>
          <p class="fw-bold text-center">The current bid for this lot now stands at
            <span class="h5 text-primary">$<%= @lot&.bids.last.amount %>.00</span>
          </p>
          <p class="text-center">
            <span class="btn btn-info px-4 fw-bold text-white" data-bs-toggle="modal"
                  data-bs-target="#new-bid">New Bid</span>
          </p>
        <% end %>

        <% if lost_lot?(current_company, @lot) && @lot&.auction.expired? %>
          <h1 class="display-3 text-center mb-sm-3 text-warning fw-bold">
            You lost
          </h1>
          <p class="fw-bold text-center">This auction has ended. Check other live auctions</p>
        <% end %>

        <% if won_lot?(@lot, current_company) %>
          <h1 class="display-3 text-center mb-sm-2 text-info fw-bold">
            Congratulations!! You won.
          </h1>
          <p class="fw-bold text-center text-info">
            An email will be sent to you with details of delivery.
          </p>
        <% end %>

        <% if @lot&.current_winner == current_company %>
          <h1 class="display-3 text-center mb-sm-2 text-info">
            You have the winning bid.
          </h1>
          <p class="fw-bold text-center text-info mb-sm-1">
            Time remaining: 45d 21h 54s
          </p>

          <div class="row d-flex rounded-4 shadow my-sm-3">
            <h1 class="display-6 text-center fw-semibold mb-sm-2">
              Your bid
            </h1>
            <div class="col-sm-8 rounded-4 px-sm-4">
              <span class="small mb-1">LOT: #<%= @lot&.lot_number %></span>

              <h1 class="display-5">
                <i class="text-dark bi-coin"></i>
                Total amount: $<%= @lot&.bids&.last&.amount %>.00
              </h1>

              <h1 class="display-5">
                <i class="text-dark bi-truck"></i>
                Delivery: <%= @lot&.bids&.last&.delivery_options %>
              </h1>

              <h1 class="display-5">
                <i class="text-dark bi-geo-fill"></i>
                Location: <%= @lot&.bids&.last&.location %>
              </h1>

              <h1 class="display-5 d-flex">
                <p class="h2 mt-1">
                  <span class="rounded border badge bg-white text-dark text-center me-3">5</span>
                </p>
                <button class="btn btn-outline-dark flex-shrink-0" type="button">
                  <i class="bi-archive me-1"></i>
                  Items
                </button>
              </h1>
            </div>
            <div class="col-sm-4 d-flex row">
              <% if @lot&.winning_bid&.images.attached? %>
                <% @lot&.winning_bid&.images.each do |image| %>
                  <%= image_tag image, class: 'col-md-6 img-fluid rounded-2 mb-sm-2', width: '400px', height: '400px' %>
                <% end %>
              <% end %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

<div class="modal fade" id="new-bid" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="exampleModalLabel"><%= "#{@lot.title.capitalize} bid" %></h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <div class="d-flex justify-content-center align-items-center">
          <div class="col-8 col-lg-6">
            <h4 class="fw-semibold text-center">Make offer</h4>
            <%= form_with(model: @bid, url: reverse_auction_lot_bids_path(@lot), method: :post, data: { turbo: false }) do |f| %>
              <div class="row g-3 mt-4 text-dark">
                <%= render 'shared/error_messages', object: f.object %>

                <div class="col-sm-12">
                  <%= f.label 'Total Amount ($)', class: 'form-label' %>
                  <%= f.number_field :amount, class: 'form-control', required: true %>
                </div>

                <div class="col-sm-12">
                  <%= f.label :delivery, class: 'form-label' %>
                  <%= select_tag :delivery_options, options_for_select(['Included in amount', 'Unavailable']), class: 'form-select', required: true %>
                </div>

                <div class="col-sm-12 mb-2 ">
                  <%= f.label "Add images", class: 'form-label' %>
                  <%= f.file_field :images, accept: 'image/*', multiple: true, class: 'form-control', required: true %>
                </div>

                <div class="text-center ">
                  <%= f.submit "Place bid", class: "text-white btn btn-info btn-md" %>
                </div>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/reverse_auction/lots/wishlist.html.erb
<div class="mb-5 bg-warning p-2 rounded text-white">
  <h3 class="display-6 fw-bold">Auctions/Wishlist</h3>
</div>

<div class="shadow row p-1 px-2 mx-2 rounded">
  <% @lots.each do |lot| %>
    <div class="border border-white shadow mb-4 col-2 me-1 rounded p-1 card">
      <div class="p-0 m-0 border-bottom border-2 border-info mb-2">
        <h5 class="h5 fw-bold float-start m-0">
          <%= lot.title.capitalize %>
        </h5>
      </div>
      <div class="">
      <span class="text-dark-emphasis">
        <% if lot.bids.any? %>
          <%  if lot.current_winner == current_company  %>
            <strong class="text-success">You are the current winner! </strong>
          <%   else   %>
            <strong class="text-dark">Winning bid:
              <%=   number_to_currency(lot.winning_bid.amount)   %>
            </strong>
          <%   end %>
        <%  else %>
          <strong class="text-dark">Asking ($): </strong>
          <%=  number_to_currency(lot.asking_price)  %>
        <%  end %>
      </span>
      </div>
      <div class="">
      <span class="text-dark-emphasis">
        <strong class="text-dark">Condition: </strong>
        <%= lot.condition %>
      </span>
      </div>
      <div class="">
      <span class="text-dark-emphasis">
        <strong class="text-dark">Quantity:</strong>
        <%= lot.quantity %>
      </span>
      </div>
      <div class="">
      <span class="text-dark-emphasis">
        <strong class="text-dark">Lot number:</strong>
        <%= lot.lot_number %>
      </span>
      </div>
      <div class="">
        <%= link_to 'View', reverse_auction_auction_lot_path(lot.auction, lot), class: 'btn btn-sm px-2 py-1 btn-outline-info fw-bold my-2' %>
        <% if lot.current_winner == current_company || lot.auction.expired? %>
        <span class="btn btn-sm px-2 py-1 btn-outline-info fw-bold my-2" data-bs-toggle="modal"
              data-bs-target=<%= "#new-bid-#{lot.id}" %>>Bid</span>
        <% end %>
        <% if lot.collected?(current_company.id) %>
          <%= link_to '', wish_reverse_auction_lot_path(lot),
                      class: 'bi-bookmark-heart-fill btn-sm btn px-2 py-1 btn-outline-info fw-bold my-2', data: { turbo_method: :post } %>
        <% else %>
          <%= link_to '', wish_reverse_auction_lot_path(lot),
                      class: 'btn-sm bi-bookmark-heart btn px-2 py-1 btn-outline-info fw-bold my-2', data: { turbo_method: :post } %>
        <% end %>
      </div>

      <div class="modal fade" id=<%= "new-bid-#{lot.id}" %> tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <h1 class="modal-title fs-5" id="exampleModalLabel"><%= "#{lot.title.capitalize} bid" %></h1>
              <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
              <div class="d-flex justify-content-center align-items-center">
                <div class="col-8 col-lg-6">
                  <h4 class="fw-semibold text-center">Make offer</h4>
                  <%= form_with(model: @bid, url: reverse_auction_lot_bids_path(lot), method: :post, data: { turbo: false }) do |f| %>
                    <div class="row g-3 mt-4 text-dark">
                      <%= render 'shared/error_messages', object: f.object %>

                      <div class="col-sm-12">
                        <%= f.label 'Total Amount ($)', class: 'form-label' %>
                        <%= f.number_field :amount, class: 'form-control', required: true %>
                      </div>

                      <div class="col-sm-12">
                        <%= f.label :delivery, class: 'form-label' %>
                        <%= select_tag :delivery_options, options_for_select(['Included in amount', 'Unavailable']), class: 'form-select', required: true %>
                      </div>

                      <div class="col-sm-12 mb-2 ">
                        <%= f.label "Add images", class: 'form-label' %>
                        <%= f.file_field :images, accept: 'image/*', multiple: true, class: 'form-control', required: true %>
                      </div>

                      <div class="text-center ">
                        <%= f.submit "Place bid", class: "text-white btn btn-info btn-md" %>
                      </div>
                    </div>
                  <% end %>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>